// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20220401202216_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 13,
                            Breed = "Celtic Setter",
                            Gender = "Female",
                            Name = "Sophie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 4,
                            Breed = "English Bulldog",
                            Gender = "Male",
                            Name = "Bucket",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 5,
                            Breed = "Coon Hound",
                            Gender = "Male",
                            Name = "Lawrence",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 6,
                            Breed = "Jack Russel Terrier",
                            Gender = "Male",
                            Name = "Gary2",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 7,
                            Breed = "Pitbull",
                            Gender = "Female",
                            Name = "Penny",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 1,
                            Breed = "Golden Retriever",
                            Gender = "Male",
                            Name = "Zane",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 4,
                            Breed = "Poodle",
                            Gender = "Male",
                            Name = "Marcus",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 3,
                            Breed = "Bull Terrier",
                            Gender = "Female",
                            Name = "Zoie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 6,
                            Breed = "Dalmation",
                            Gender = "Female",
                            Name = "Spot",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 5,
                            Breed = "Beagle",
                            Gender = "Female",
                            Name = "Lucky",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 12,
                            Breed = "Orange Tabby",
                            Gender = "Female",
                            Name = "Charlie",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 4,
                            Breed = "Maine Coon",
                            Gender = "Male",
                            Name = "Dog",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 5,
                            Breed = "Scottish Fold",
                            Gender = "Male",
                            Name = "Beans",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 6,
                            Breed = "Russian Blue",
                            Gender = "Male",
                            Name = "Dave",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 7,
                            Breed = "Tabby",
                            Gender = "Female",
                            Name = "Oona",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 16,
                            Age = 1,
                            Breed = "Bengal",
                            Gender = "Male",
                            Name = "Oliver",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 17,
                            Age = 4,
                            Breed = "Siamese",
                            Gender = "Male",
                            Name = "Zero",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 18,
                            Age = 3,
                            Breed = "Sphynx",
                            Gender = "Female",
                            Name = "LeeLoo",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 19,
                            Age = 6,
                            Breed = "Oriental Shorthair",
                            Gender = "Female",
                            Name = "Madame Princess Cat",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 20,
                            Age = 5,
                            Breed = "Persian",
                            Gender = "Female",
                            Name = "Boo",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
